# Site settings
title: Les sages
description: >-
   Site du podcast "Les "Sages""
lang: fr
timezone: Europe/Paris
image: assets/img/site_web_entete.png # This image used for Open Graph more info https://ogp.me/
repo: #https://github.com/piharpi/mahendrata.now.sh
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Les "Sages"
  bio: >-
    Podcast bi-mensuel, rempli d'anecdotes de sages-femmes. Si vous aussi, vous travaillez dans le milieu de la périnatalité et que vous voulez raconter une histoire, sentez vous libre de <b> m'envoyer un <a href="mailto:les.sages@mailo.com"> mail</a>.</b>
  username: username
  email: les.sages@mailo.com
  avatar: assets/img/avatar_new.jpg

# Url settings
url: #"https://klise.now.sh"
baseurl: /lessages
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: [birth, naissance, sage-femme, anecdote, expérience, études, vécu]
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles

podcast:
  title: Les "Sages"
  description: Chroniques de sages-femmes & anecdotes de naissance. Avez-vous toujours eu l'envie de voir l'envers du décors de nos gardes de 12h ? Entre rétention urinaire, aller-retour sans fin dans les salles de naissance, et pleurs de douleurs ou de joie... bienvenue à la maternité. Si vous aussi, vous avez une anecdotes à partager, écrivez-nous avec l'adresse mail disponible sur notre site web.
  url: podcast.xml # podcast xml url
  author: Les "Sages"
  email: les.sages@mailo.com
  logo: assets/img/logo_podcast.jpg
 # logo in 1400 – 3000 pixel
  language: fr # http://www.loc.gov/standards/iso639-2/php/code_list.php
  category: Health &amp; Fitness # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: Medicine
  type: episodic # episodic | serial
  explicit: true # true | false
  complete: no # 'yes' | 'no'
  block: no # 'yes' | 'no'
